"""Route composition: router prefixes, across module boundaries.

RFC-0001's Problem section is this case. `server.py` mounts a router created with
`APIRouter(prefix="/api")`; a handler in `routes/health.py` is decorated
`@router.get("/health")`. The route is `/api/health`, and the spike confirmed it
against a running container: `/api/health -> 200`, `/health -> 404`. A detector that
reports the decorator literal writes an Ingress that 404s while kustomize build,
kubeconform and docker build all pass -- "confident and wrong", generated by the tool
this RFC describes.

So composition is the whole job, and refusing to compose is the other half of it: when
any prefix in the chain is not a literal, this module emits a gap naming the expression
and reports no route at all.
"""

from __future__ import annotations

import ast
from pathlib import Path

from spec import Evidence, Gap, Route, gap_id
from walk import rel, walk_files

HTTP_METHODS = ("get", "post", "put", "patch", "delete", "head", "options")


class _Undecidable:
    """A prefix that is an expression rather than a literal."""

    def __init__(self, expression: str = "", path: str = "", line: int = 0):
        self.expression = expression
        self.path = path
        self.line = line

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"UNDECIDABLE({self.expression!r})"


UNDECIDABLE = _Undecidable


def join_path(*parts: str) -> str:
    """Concatenate path segments into one normalised absolute path."""
    joined = "/".join(part.strip("/") for part in parts if part and part.strip("/"))
    return "/" + joined if joined else "/"


def _literal_or_undecidable(node: ast.AST | None, path: str) -> "str | _Undecidable":
    """A string literal, or a marker carrying the expression we could not evaluate."""
    if node is None:
        return ""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return _Undecidable(ast.unparse(node), path, getattr(node, "lineno", 0))


def _kwarg(call: ast.Call, name: str) -> "ast.AST | None":
    for keyword in call.keywords:
        if keyword.arg == name:
            return keyword.value
    return None


class _Module:
    """What one Python module says about routers."""

    def __init__(self, dotted: str, path: str):
        self.dotted = dotted
        self.path = path
        self.apps: set[str] = set()
        self.routers: dict[str, "str | _Undecidable"] = {}
        self.router_lines: dict[str, int] = {}
        self.handlers: dict[str, list[tuple[str, int]]] = {}
        self.includes: list[tuple[str, str, "str | _Undecidable", int]] = []
        self.aliases: dict[str, tuple[str, str]] = {}


def _parse_module(text: str, dotted: str, path: str) -> "_Module | None":
    module = _Module(dotted, path)
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return None

    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            for alias in node.names:
                module.aliases[alias.asname or alias.name] = (node.module, alias.name)

        elif isinstance(node, ast.Assign) and isinstance(node.value, ast.Call):
            func = node.value.func
            called = func.id if isinstance(func, ast.Name) else getattr(func, "attr", None)
            target = node.targets[0]
            if not isinstance(target, ast.Name):
                continue
            if called == "FastAPI":
                module.apps.add(target.id)
            elif called == "APIRouter":
                module.routers[target.id] = _literal_or_undecidable(
                    _kwarg(node.value, "prefix"), path
                )
                module.router_lines[target.id] = node.lineno

        elif isinstance(node, ast.Call):
            func = node.func
            if not isinstance(func, ast.Attribute) or func.attr != "include_router":
                continue
            if not isinstance(func.value, ast.Name) or not node.args:
                continue
            child = node.args[0]
            if not isinstance(child, ast.Name):
                continue
            module.includes.append((
                func.value.id,
                child.id,
                _literal_or_undecidable(_kwarg(node, "prefix"), path),
                node.lineno,
            ))

        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            for decorator in node.decorator_list:
                if not isinstance(decorator, ast.Call):
                    continue
                attribute = decorator.func
                if not isinstance(attribute, ast.Attribute):
                    continue
                if attribute.attr not in HTTP_METHODS:
                    continue
                if not isinstance(attribute.value, ast.Name) or not decorator.args:
                    continue
                literal = _literal_or_undecidable(decorator.args[0], path)
                if isinstance(literal, _Undecidable):
                    continue
                module.handlers.setdefault(attribute.value.id, []).append(
                    (literal, decorator.lineno)
                )
    return module


def detect_routes(
    root: Path, directory: Path, service_name: str
) -> tuple[list[Route], list[Gap], list[Evidence]]:
    """Compose every mounted route in the service tree.

    Walks the whole tree, not the entry module: real backends put routers under
    `routes/` and the entry module only mounts them.
    """
    modules: dict[str, _Module] = {}
    for path in walk_files(directory, suffixes=(".py",)):
        dotted = path.relative_to(directory).with_suffix("").as_posix().replace("/", ".")
        parsed = _parse_module(path.read_text(encoding="utf-8"), dotted, rel(root, path))
        if parsed is not None:
            modules[dotted] = parsed

    def resolve(module: _Module, local_name: str) -> "tuple[_Module, str] | None":
        """A name used in include_router, resolved to the module that defines it."""
        if local_name in module.routers:
            return module, local_name
        target = module.aliases.get(local_name)
        if target is None:
            return None
        other = modules.get(target[0])
        if other is None or target[1] not in other.routers:
            return None
        return other, target[1]

    routes: list[Route] = []
    gaps: list[Gap] = []
    evidence: list[Evidence] = []
    undecidable: list[_Undecidable] = []
    seen: set[tuple[str, str]] = set()

    def descend(module: _Module, holder: str, prefix: str, depth: int) -> None:
        if depth > 16:      # a cycle in include_router; refuse rather than recurse
            return
        for parent, child, include_prefix, line in module.includes:
            if parent != holder:
                continue
            resolved = resolve(module, child)
            if resolved is None:
                continue
            child_module, child_name = resolved
            child_prefix = child_module.routers[child_name]

            for part in (include_prefix, child_prefix):
                if isinstance(part, _Undecidable):
                    undecidable.append(part)
            if isinstance(include_prefix, _Undecidable) or isinstance(child_prefix, _Undecidable):
                continue

            here = join_path(prefix, include_prefix, child_prefix)
            evidence.append(Evidence(path=module.path, line=line))

            for handler_path, handler_line in child_module.handlers.get(child_name, []):
                composed = join_path(here, handler_path)
                key = (child_module.path, composed)
                if key in seen:
                    continue
                seen.add(key)
                routes.append(Route(
                    host=None, path=composed, service=service_name, port=None, tls=False
                ))
                evidence.append(Evidence(path=child_module.path, line=handler_line))

            descend(child_module, child_name, here, depth + 1)

    for module in sorted(modules.values(), key=lambda item: item.dotted):
        for app_name in sorted(module.apps):
            descend(module, app_name, "", 0)

    if undecidable:
        first = min(undecidable, key=lambda item: (item.path, item.line))
        gaps.append(Gap(
            id=gap_id("service", service_name, "routes", "prefix"),
            kind="value",
            pointers=[],   # zero pointers: the answer sets paths this run has no entries for
            question=(
                f"What is the mounted path prefix for `{service_name}`? "
                f"`{first.path}` line {first.line} mounts a router with "
                f"`prefix={first.expression}`, which is read from configuration rather "
                f"than written in the repository, so the routes cannot be composed. "
                f"Answer with the prefix this application actually serves on in "
                f"production (for example `/api`). Reporting the decorator literal "
                f"instead would generate an Ingress that returns 404 while every "
                f"manifest check passes."
            ),
            proposed=None,
            confidence="low",
            severity="blocking",
            evidence=[f"{first.path}:{first.line}"],
            evidence_scope=[rel(root, directory)],
        ))
        # Refuse to compose. Partial routes from the decidable branches would be a
        # more convincing kind of wrong than none at all.
        routes = []
        evidence = []

    routes.sort(key=lambda route: route.path)
    evidence.sort(key=lambda item: (item.path, item.line))
    return routes, gaps, evidence
