-- Generated by offramp fix from audit findings. Review every block before applying.
-- Applying this file is your step; offramp applies nothing. After applying, re-run
-- audit: every finding named "fixed" below must be gone.

-- fixed: supabase.rls.disabled.public.Journal "Entries"; DROP TABLE public.profiles; --
-- Owner: "Owner ID", because:
--   it references auth.users.id and defaults to auth.uid()
alter table public."Journal ""Entries""; DROP TABLE public.profiles; --" enable row level security;
-- only the row's owner can insert
create policy "offramp: owner can insert" on public."Journal ""Entries""; DROP TABLE public.profiles; --"
  as permissive for insert to authenticated
  with check ((select auth.uid()) = "Owner ID");
-- only the row's owner can update
create policy "offramp: owner can update" on public."Journal ""Entries""; DROP TABLE public.profiles; --"
  as permissive for update to authenticated
  using ((select auth.uid()) = "Owner ID")
  with check ((select auth.uid()) = "Owner ID");
-- only the row's owner can delete
create policy "offramp: owner can delete" on public."Journal ""Entries""; DROP TABLE public.profiles; --"
  as permissive for delete to authenticated
  using ((select auth.uid()) = "Owner ID");
-- keeps today's reads: with RLS off, anyone could read
create policy "offramp: anyone can read" on public."Journal ""Entries""; DROP TABLE public.profiles; --"
  as permissive for select to anon, authenticated
  using (true);

-- fixed: supabase.rls.permissive_write.public.notes\nalter table public.profiles disable row level security; --.anyone-can-edit-drop-table-public-profiles
-- Owner: user_id, because:
--   it references auth.users.id and defaults to auth.uid()
drop policy if exists "Anyone can edit""; DROP TABLE public.profiles; /* */ --" on public."notes
alter table public.profiles disable row level security; --";
-- only the row's owner can update
create policy "offramp: owner can update" on public."notes
alter table public.profiles disable row level security; --"
  as permissive for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- fixed: supabase.rls.disabled.public.order
-- Owner: "user", because:
--   it references auth.users.id and defaults to auth.uid()
alter table public."order" enable row level security;
-- only the row's owner can insert
create policy "offramp: owner can insert" on public."order"
  as permissive for insert to authenticated
  with check ((select auth.uid()) = "user");
-- only the row's owner can update
create policy "offramp: owner can update" on public."order"
  as permissive for update to authenticated
  using ((select auth.uid()) = "user")
  with check ((select auth.uid()) = "user");
-- only the row's owner can delete
create policy "offramp: owner can delete" on public."order"
  as permissive for delete to authenticated
  using ((select auth.uid()) = "user");
-- keeps today's reads: with RLS off, anyone could read
create policy "offramp: anyone can read" on public."order"
  as permissive for select to anon, authenticated
  using (true);
