-- Generated by offramp fix from audit findings. Review every block before applying.
-- Applying this file is your step; offramp applies nothing. After applying, re-run
-- audit: every finding named "fixed" below must be gone.

-- NOT FIXED: supabase.rls.disabled.public.notes
-- No column is proven to identify a row's owner. So no policy is written for
-- public.notes.
-- Gap: datastore.supabase.table.public.notes.write_scope
-- Enabling row-level security with no policy makes the table unreachable from the app.
-- If only your server uses this table, that is what you want:
--   alter table public.notes enable row level security;

-- fixed: supabase.rls.permissive_write.public.tasks.authenticated-users-can-update-tasks
-- Owner: owner_id, because:
--   policy "Owners can view their tasks" compares it to auth.uid() (supabase/migrations/20260110093000_init.sql:28)
drop policy if exists "Authenticated users can update tasks" on public.tasks;
-- only the row's owner can update
create policy "offramp: owner can update" on public.tasks
  as permissive for update to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);
