"""The fix renderer: a plan becomes a migration, FIXES.md and fixes.json. RFC-0003.

RFC-0001's renderer in every respect: a pure function of the AppSpec, the audit document
and the migration version, byte-stable, with no clock, no network and no model. It reads
no source file. `fix.py` supplies the inputs, checks the output by round trip and writes
it, and `verify.py` re-renders it.

The migration holds one block per table, in table order. A fixed table's block says which
findings it closes and why the owner column is the owner. An unfixed table's block is
comments only: an enabled table with no policy would lock the app out, and it would
make the finding disappear without its question being answered.
"""

from __future__ import annotations

import textwrap
from dataclasses import asdict, dataclass

from checks.supabase import DISABLED
from fix_plan import (
    OWNED_COMMANDS, FixPlan, Outcome, TableFix, Unfixed, plan_fix, supabase_schema,
)
from fix_sql import (
    create_policy, drop_policy, enable_rls, quote_ident, quote_table, sql_comment,
)
from rls import ANYONE
from spec import AppSpec, canonical_json

SCHEMA = "offramp.fix/1"
MIGRATION_SUFFIX = "_offramp_rls.sql"
MIGRATIONS = "supabase/migrations"
_WIDTH = 88

HEADER = (
    "Generated by offramp fix from audit findings. Review every block before applying.",
    "Applying this file is your step; offramp applies nothing. After applying, re-run",
    'audit: every finding named "fixed" below must be gone.',
)


@dataclass(frozen=True)
class Rendering:
    files: dict[str, str]          # relative path -> content; empty when nothing to say
    plan: FixPlan
    migration: str | None          # its path, when one is written
    statements: int                # executable statements in the migration

    @property
    def outcomes(self) -> tuple[Outcome, ...]:
        return self.plan.outcomes

    @property
    def expected_after(self) -> list[str]:
        return self.plan.expected_after


def default_version(appspec: AppSpec) -> str | None:
    """`Schema.latest + 1`, keeping its width. Derived from the repository, so it sorts
    after every migration in it and is the same on every run over the same commit."""
    schema = supabase_schema(appspec)
    return None if schema is None else next_version(schema.latest)


def next_version(latest: str | None) -> str | None:
    return None if latest is None else str(int(latest) + 1).zfill(len(latest))


def migration_path(version: str) -> str:
    return f"{MIGRATIONS}/{version}{MIGRATION_SUFFIX}"


def render_fix(appspec: AppSpec, document: dict, version: str) -> Rendering:
    plan = plan_fix(appspec, document)
    if not plan.outcomes:
        return Rendering(files={}, plan=plan, migration=None, statements=0)
    files: dict[str, str] = {}
    path, statements = None, 0
    if plan.fixes:
        path = migration_path(version)
        files[path], statements = _migration(plan)
    files["FIXES.md"] = _fixes_md(plan, document, path)
    files["fixes.json"] = canonical_json({
        "schema": SCHEMA,
        "app": document["app"],
        "version": version,
        "migration": path,
        "statements": statements,
        "findings": [asdict(outcome) for outcome in plan.outcomes],
        "expected_after": plan.expected_after,
    })
    return Rendering(files=files, plan=plan, migration=path, statements=statements)


# -- the migration ------------------------------------------------------------------------

def _comments(text: str) -> list[str]:
    """Prose as comment lines. Escaped before wrapping, so a newline in an identifier
    stays visible and cannot end the comment."""
    escaped = sql_comment(text)[3:]
    return ["-- " + line for line in textwrap.wrap(
        escaped, _WIDTH - 3, break_long_words=False, break_on_hyphens=False)]


def _migration(plan: FixPlan) -> tuple[str, int]:
    blocks: list[tuple[str, list[str], int]] = []
    for fix in plan.fixes:
        blocks.append((fix.table.name, *_fix_block(fix)))
    for unfixed in plan.unfixed:
        blocks.append((unfixed.table.name, _unfixed_block(unfixed), 0))
    blocks.sort(key=lambda block: block[0])
    lines = [sql_comment(line) for line in HEADER] + [""]
    for _, block, _ in blocks:
        lines += block + [""]
    return "\n".join(lines).rstrip() + "\n", sum(count for _, _, count in blocks)


def _fix_block(fix: TableFix) -> tuple[list[str], int]:
    name = fix.table.name
    lines = [sql_comment(f"fixed: {finding}") for finding in fix.fixed]
    if fix.scope.kind == "owner":
        lines.append(sql_comment(f"Owner: {quote_ident(fix.scope.column)}, because:"))
        lines += [sql_comment(f"  {basis}") for basis in fix.scope.basis or ["you answered so"]]
        anonymous = [p.name for p in fix.drops if any(r in ANYONE for r in p.roles)]
        if anonymous and fix.creates:
            lines += _comments(
                f'"{anonymous[0]}" was granted to anyone. Its replacements are granted to '
                f"authenticated: auth.uid() is null for a request that is not signed in, "
                f"so an owner check granted to anon could never pass.")
    else:
        lines += _comments("Scope: server_only (your answer). Only your server writes to "
                           "this table, with a key that bypasses row-level security, so no "
                           "policy is created.")
    for command, existing in fix.covered:
        lines.append(sql_comment(f'{command}: already covered by "{existing}".'))
    statements: list[str] = []
    if fix.enable:
        statements.append(enable_rls(name))
    statements += [drop_policy(policy.name, name) for policy in fix.drops]
    body = list(statements)
    for policy in fix.creates:
        body.append(sql_comment(policy.why))
        body.append(create_policy(policy.name, name, policy.command, sorted(policy.roles),
                                  policy.using, policy.with_check))
    return lines + body, len(statements) + len(fix.creates)


def _unfixed_block(unfixed: Unfixed) -> list[str]:
    name = unfixed.table.name
    lines = [sql_comment(f"NOT FIXED: {finding}") for finding in unfixed.findings]
    lines += _comments(f"{unfixed.reason} So no policy is written for {name}.")
    lines.append(sql_comment(f"Gap: {unfixed.gap}"))
    if any(finding.startswith(DISABLED + ".") for finding in unfixed.findings):
        lines += _comments("Enabling row-level security with no policy makes the table "
                           "unreachable from the app. If only your server uses this table, "
                           "that is what you want:")
        lines.append(sql_comment(f"  {enable_rls(name)}"))
    for policy in unfixed.open_policies:
        lines += _comments("Dropping the open policy leaves this change to your server "
                           "alone. If that is what you want:")
        lines.append(sql_comment(f"  {drop_policy(policy, name)}"))
    return lines


# -- FIXES.md -----------------------------------------------------------------------------

def _heading(app: dict) -> str:
    detail = [app["platform"]]
    if app.get("commit"):
        detail.append(app["commit"][:7])
    return f"# Row-level-security fixes: {app['name'] or '(unnamed)'} ({', '.join(detail)})"


def _fixes_md(plan: FixPlan, document: dict, path: str | None) -> str:
    counts = {status: sum(1 for o in plan.outcomes if o.status == status)
              for status in ("fixed", "gap", "not_in_scope")}
    titles = {f["id"]: f["title"] for f in document["findings"]}
    lines = [
        _heading(document["app"]), "",
        f"{counts['fixed']} fixed · {counts['gap']} need your answer · "
        f"{counts['not_in_scope']} left for your decision", "",
    ]
    if path:
        lines += [f"`offramp fix` wrote `{path}` for you to review. It is a staging copy: "
                  "nothing has been applied, and nothing in your repository or your "
                  "database has changed.", ""]
    else:
        lines += ["No migration was written: nothing here can be fixed without a decision "
                  "from you. Nothing in your repository or your database has changed.", ""]
    if plan.fixes:
        lines += ["## What the migration changes", ""]
        for fix in plan.fixes:
            lines += _fix_section(fix, titles)
    if plan.unfixed:
        lines += ["## Needs your answer", ""]
        for unfixed in plan.unfixed:
            lines += [f"### `{unfixed.table.name}`", "", unfixed.reason, ""]
            lines += [f"- {titles[f]} (`{f}`)" for f in unfixed.findings]
            lines += [f"- Answer the gap `{unfixed.gap}` with the owner column, or "
                      "`server_only` if only your server writes to this table. Until then "
                      "the migration holds only a commented-out block for it.", ""]
    decisions = [o for o in plan.outcomes if o.status == "not_in_scope"]
    if decisions:
        lines += ["## Deliberately not changed", ""]
        lines += [f"- {titles[o.id]} (`{o.id}`). {o.reason}" for o in decisions]
        lines.append("")
    if path:
        lines += ["## Applying it", "",
                  f"1. Read `{path}` block by block. Each says what it closes and why.",
                  f"2. Copy it, unchanged, into your repository's `{MIGRATIONS}/`.",
                  "3. Apply it through your project's usual migration process, as one "
                  "migration, so no table is ever between a dropped policy and its "
                  "replacement.",
                  "4. Re-run `audit`. Every finding listed as fixed must be gone. Re-run "
                  "`fix` as well: it writes a new file only for what remains.", ""]
    lines += ["## What this cannot see", "",
              "- **Grants.** Policies decide which rows; grants decide whether a role may "
              "run the operation at all. On a project that no longer grants table access "
              "to `authenticated` by default, the owner policies are only reached once "
              "that grant exists.",
              "- **Views and security-definer functions.** Both can read a table without "
              "its policies. A view over a fixed table needs `security_invoker`.",
              "- **Policies made in the Supabase dashboard.** They never reach "
              "`supabase/migrations/`. Run the dashboard's Security Advisor after applying.",
              "", "---", "",
              "Generated by [offramp](https://github.com/devopsgenie-ai/offramp) fix. "
              "Re-run it on the same commit to reproduce these files.", ""]
    return "\n".join(lines).rstrip() + "\n"


def _fix_section(fix: TableFix, titles: dict[str, str]) -> list[str]:
    table = fix.table
    lines = [f"### `{table.name}`", ""]
    lines += [f"- Closes: {titles[f]} (`{f}`)" for f in fix.fixed]
    if fix.enable:
        lines.append("- Turns row-level security on.")
        waking = [p for p in table.policies if p not in fix.drops]
        if waking:
            lines.append("- These policies were written earlier but do nothing while "
                         "row-level security is off. They take effect now: "
                         + ", ".join(f'"{p.name}" ({p.evidence})' for p in waking) + ".")
    for policy in fix.drops:
        lines.append(f'- Removes the policy "{policy.name}" ({policy.evidence}). To undo, '
                     f"re-create it from that line.")
    if fix.scope.kind == "server_only":
        lines += ["- Adds no policy: only your server, with a key that bypasses row-level "
                  "security, may change this table (your answer).", ""]
        return lines
    column = fix.scope.column
    lines.append(f"- The owner of a row is the user in `{column}`, because "
                 f"{'; and '.join(fix.scope.basis)}.")
    commands = [p.command for p in fix.creates if p.command in OWNED_COMMANDS]
    if commands:
        verbs = {"insert": "add", "update": "change", "delete": "delete"}
        lines.append(f"- Signed-in users can {_join([verbs[c] for c in commands])} only "
                     f"rows whose `{column}` is their own.")
    for command, existing in fix.covered:
        lines.append(f'- "{existing}" already limits {command}s to the owner, so it is '
                     f"kept and nothing is added for {command}.")
    reads = [p for p in fix.creates if p.command == "select"]
    for policy in reads:
        if policy.kept_from:
            lines.append(f'- Reads are unchanged: the read half of "{policy.kept_from}" is '
                         f'kept as "{policy.name}".')
        else:
            lines.append(f"- Reads are unchanged: anyone can still read every row, as today, "
                         f'through "{policy.name}". The audit will now ask whether that is '
                         f"intended.")
    columns = {c.name: c for c in table.columns or []}
    owner = columns.get(column)
    if owner is not None and owner.nullable:
        lines.append(f"- `{column}` allows NULL. A row with no owner becomes unreachable "
                     f"from the app. Count them before applying: `select count(*) from "
                     f"{quote_table(table.name)} where {quote_ident(column)} is null;`")
    if owner is not None and "insert" in commands and owner.default != "auth.uid()":
        lines.append(f"- `{column}` has no default of `auth.uid()`, so the app must set it "
                     f"to the signed-in user's id on every insert, or the insert is "
                     f"refused. `alter table {quote_table(table.name)} alter column "
                     f"{quote_ident(column)} set default auth.uid();` does it for you.")
    kept = [p for p in table.policies if p not in fix.drops]
    has_reader = any(p.command in ("select", "all") for p in kept + list(fix.creates))
    if "update" in commands and not has_reader:
        lines.append("- The table has no SELECT policy, so an update from the app finds no "
                     "rows and silently changes nothing. That was true before this fix too.")
    lines.append("")
    return lines


def _join(words: list[str]) -> str:
    return words[0] if len(words) == 1 else ", ".join(words[:-1]) + " and " + words[-1]

