"""Renderers: AppSpec -> {relative path: file content}. Pure functions.

SPIKE revision 2. Every function takes an AppSpec and returns strings. Nothing
reads the source repository (AGENTS.md §6), nothing reads the clock or the
environment (AGENTS.md §3), nothing writes a file. render.py does the writing.

Two rules from SPIKE.md are enforced structurally here:

  #13/#22  Every value a renderer supplies that the AppSpec did not carry goes
           through DEFAULTS and emits a `# offramp: unresolved gap <id>` marker
           naming the gap it stands in for. Revision 1 let renderer defaults
           silently substitute for undetected values, where no gap counted them
           and no truth.yaml compared against them.

  #7       Those markers are built with spec.gap_id() from names in the AppSpec,
           because a renderer is given the AppSpec and gaps are not in it. That is
           a real constraint on the id scheme and RFC-0001 does not state it.
           scripts/spike_check.sh asserts every id named in the tree exists in
           gaps.json, which makes both rules checkable rather than aspirational.

Placeholders for unanswered inputs are spelled REPLACE-ME-*, in uppercase where
the field permits it: an uppercase registry is not a valid image reference, so an
unanswered blocking gap fails at `docker pull` with a clear message rather than
resolving to something plausible. The app name is the exception -- it lands in
namespace and label positions that must stay DNS-1123 valid for the output to
validate at all -- so it is lowercase and greppable instead.
"""

from __future__ import annotations

import json
import shlex
from dataclasses import dataclass
from typing import Any

from spec import AppSpec, Service, gap_id


@dataclass(frozen=True)
class Default:
    """A value the renderer supplies, and the gap it stands in for."""

    value: Any
    gap: str


# The renderer's whole vocabulary of invented values. Nothing outside this table
# may put an undetected value into the output.
def default_python(service: Service) -> Default:
    return Default("3.11", gap_id("service", service.build.context, "runtime", "version"))


def default_node(service: Service) -> Default:
    return Default("20", gap_id("service", service.build.context, "runtime", "version"))


def default_port(service: Service) -> Default:
    # #3: the port of a service compiled to static assets. The only port in the
    # source is the CRA dev server's 3000, which is wrong for the container that
    # ships, so this belongs to the renderer that chose the web server.
    return Default(8080, gap_id("service", service.build.context, "ports"))


def default_probes(service: Service) -> Default:
    from spec import Probe

    port = default_port(service).value
    return Default(
        [
            Probe("liveness", "/", port, "http", 15, 20),
            Probe("readiness", "/", port, "http", 5, 10),
        ],
        gap_id("service", service.build.context, "probes"),
    )


PLACEHOLDER_NAME = Default("replace-me-app-name", gap_id("app", "name"))
PLACEHOLDER_REGISTRY = Default("REPLACE-ME-registry", gap_id("delivery", "image_registry"))
PLACEHOLDER_REPO = Default("REPLACE-ME-repo-url", gap_id("delivery", "gitops_repo_url"))

NGINX_IMAGE = "nginxinc/nginx-unprivileged:1.27-alpine"
BANNER = "# Generated by offramp. Edits here are overwritten; change the AppSpec instead."


def marker(default: Default, *notes: str) -> list[str]:
    return [f"# offramp: unresolved gap {default.gap}"] + [f"#   {note}" for note in notes]


def app_name(appspec: AppSpec) -> str:
    return appspec.name or PLACEHOLDER_NAME.value


def namespace_of(appspec: AppSpec, environment) -> str:
    return environment.namespace or f"{app_name(appspec)}-{environment.name}"


def serving_port(service: Service) -> int:
    return service.ports[0] if service.ports else default_port(service).value


def labels(appspec: AppSpec, service: Service) -> list[tuple[str, str]]:
    return sorted(
        {
            "app.kubernetes.io/name": service.name,
            "app.kubernetes.io/part-of": app_name(appspec),
        }.items()
    )


def secret_name(appspec: AppSpec, service: Service, key: str) -> str:
    for datastore in appspec.datastores:
        if key in datastore.env_keys and service.name in datastore.consumed_by:
            # #25: keyed on the datastore's own name, not its kind.
            return f"{app_name(appspec)}-{datastore.name}"
    return f"{app_name(appspec)}-{service.name}"


def config_name(service: Service) -> str:
    return f"{service.name}-config"


def yaml_block(lines: list[str]) -> str:
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Dockerfiles
# ---------------------------------------------------------------------------

def render_dockerfile(appspec: AppSpec, service: Service) -> str:
    context = service.build.context
    header = [
        BANNER,
        f"# service: {service.name} ({service.role}, {service.runtime.language})",
        "#",
        "# Build context is the repository root, not the service directory: the frontend",
        "# image needs a generated file (nginx.conf) as well as application source, and",
        "# a Dockerfile cannot COPY from outside its context. See .offramp/README.md.",
        "#",
        f"#   docker build -f services/{service.name}/Dockerfile -t {service.name} .",
        "",
    ]
    body = (
        _static_dockerfile(appspec, service, context)
        if service.build.output_dir
        else _runtime_dockerfile(service, context)
    )
    return yaml_block(header + body)


def _runtime_dockerfile(service: Service, context: str) -> list[str]:
    lines: list[str] = []
    version = service.runtime.version
    if version is None:
        chosen = default_python(service)
        version = chosen.value
        lines += marker(chosen, f"No version is pinned in {context}/. Using {version}.")
    command = shlex.split(service.build.start_cmd or "")
    return lines + [
        f"FROM python:{version}-slim",
        "",
        "ENV PYTHONDONTWRITEBYTECODE=1 \\",
        "    PYTHONUNBUFFERED=1",
        "",
        "WORKDIR /app",
        "",
        f"COPY {context}/requirements.txt ./",
        f"RUN {service.build.install_cmd}",
        "",
        f"COPY {context}/ ./",
        "",
        "RUN useradd --system --uid 10001 --no-create-home app \\",
        "    && chown -R 10001:0 /app",
        "USER 10001",
        "",
        *[f"EXPOSE {port}" for port in service.ports],
        "",
        f"CMD {json.dumps(command)}",
    ]


def _static_dockerfile(appspec: AppSpec, service: Service, context: str) -> list[str]:
    lines: list[str] = []
    version = service.runtime.version
    if version is None:
        chosen = default_node(service)
        version = chosen.value
        lines += marker(chosen, f"No version is pinned in {context}/. Using {version}.")
    lines += [
        f"FROM node:{version}-alpine AS build",
        "",
        "WORKDIR /app",
        "",
        f"COPY {context}/package.json ./",
        f"RUN {service.build.install_cmd}",
        "",
        f"COPY {context}/ ./",
        "",
    ]
    # #29: derived from env, which is the single record of this fact. There is no
    # Build.args to fall out of step with it.
    for var in sorted(
        (v for v in service.env if v.binding == "build_arg"), key=lambda v: v.name
    ):
        if var.value is None:
            lines += [
                f"# offramp: unresolved gap "
                f"{gap_id('service', context, 'env', var.name, 'value')}"
            ]
        lines += [
            f"#   {var.name} is substituted into the JavaScript bundle at build time.",
            "#   Pass it with --build-arg; a ConfigMap cannot change it afterwards.",
            f"ARG {var.name}" + (f"={json.dumps(var.value)}" if var.value is not None else ""),
            f"ENV {var.name}=${var.name}",
            "",
        ]
    lines += [
        f"RUN {service.build.build_cmd}",
        "",
    ]
    if not service.ports:
        lines += marker(
            default_port(service),
            "The web server serving the compiled bundle, and its port, are offramp's",
            "choice: the application has neither.",
        )
    lines += [
        f"FROM {NGINX_IMAGE}",
        "",
        f"COPY --from=build /app/{service.build.output_dir} /usr/share/nginx/html",
        f"COPY services/{service.name}/nginx.conf /etc/nginx/conf.d/default.conf",
        "",
        f"EXPOSE {serving_port(service)}",
    ]
    return lines


def render_nginx_conf(appspec: AppSpec, service: Service) -> str:
    return yaml_block(
        [
            BANNER,
            "",
            "server {",
            f"    listen {serving_port(service)};",
            "    server_name _;",
            "    root /usr/share/nginx/html;",
            "",
            "    # Single-page app: unknown paths are routed by the client, not the server.",
            "    location / {",
            "        try_files $uri $uri/ /index.html;",
            "    }",
            "}",
        ]
    )


def render_dockerignore(appspec: AppSpec) -> str:
    return yaml_block(
        [
            BANNER,
            "# Build context is the repository root; keep these out of it.",
            "",
            ".git",
            ".offramp",
            "**/__pycache__",
            "**/node_modules",
            "**/.env",
            "**/build",
            "**/dist",
        ]
    )


# ---------------------------------------------------------------------------
# Kustomize base
# ---------------------------------------------------------------------------

def render_configmap(appspec: AppSpec, service: Service) -> str | None:
    """Literal, non-secret runtime values.

    Only binding "runtime" appears here. A build_arg in a ConfigMap is the failure
    RFC-0001's EnvVar.binding exists to prevent: the value is already compiled into
    the bundle and the ConfigMap changes nothing.
    """
    entries = [
        var
        for var in service.env
        if var.binding == "runtime" and not var.sensitive and var.value is not None
    ]
    if not entries:
        return None
    lines = [
        BANNER,
        "apiVersion: v1",
        "kind: ConfigMap",
        "metadata:",
        f"  name: {config_name(service)}",
        "  labels:",
        *[f"    {key}: {value}" for key, value in labels(appspec, service)],
        "data:",
    ]
    for var in sorted(entries, key=lambda v: v.name):
        lines.append(f"  {var.name}: {json.dumps(var.value)}")
    return yaml_block(lines)


def _env_entries(appspec: AppSpec, service: Service) -> list[str]:
    lines: list[str] = []
    for var in sorted(service.env, key=lambda v: v.name):
        if var.binding != "runtime":
            continue
        # #4: the reference is chosen on `sensitive`, not on `source`. MONGO_URL is
        # datastore-sourced and a credential; under RFC-0001's single enum only one
        # of those could be recorded, and the secret rule keyed on the wrong one.
        if var.sensitive:
            lines += [
                f"            - name: {var.name}",
                "              valueFrom:",
                "                secretKeyRef:",
                f"                  name: {secret_name(appspec, service, var.name)}",
                f"                  key: {var.name}",
            ]
        elif var.value is not None:
            lines += [
                f"            - name: {var.name}",
                "              valueFrom:",
                "                configMapKeyRef:",
                f"                  name: {config_name(service)}",
                f"                  key: {var.name}",
            ]
    return lines


def _probes_for(appspec: AppSpec, service: Service) -> tuple[list, list[str]]:
    """-> (probes, marker lines). Supplies probes for a static service, under #22."""
    if service.probes:
        return service.probes, []
    if not service.build.output_dir:
        return [], []
    chosen = default_probes(service)
    return chosen.value, marker(
        chosen,
        "This service has no health endpoint of its own. The probes below ask the",
        "generated web server for / and pass as soon as the page is served, which",
        "does not prove the app can reach the API.",
    )


def render_deployment(appspec: AppSpec, service: Service) -> str:
    selector = labels(appspec, service)
    probes, probe_marker = _probes_for(appspec, service)
    ports = service.ports or [serving_port(service)]
    port_marker = [] if service.ports or not service.build.output_dir else marker(
        default_port(service), "The container port below is offramp's choice."
    )
    lines = [BANNER, *port_marker, *probe_marker]
    lines += [
        "apiVersion: apps/v1",
        "kind: Deployment",
        "metadata:",
        f"  name: {service.name}",
        "  labels:",
        *[f"    {key}: {value}" for key, value in selector],
        "spec:",
        f"  replicas: {service.replicas}",
        "  selector:",
        "    matchLabels:",
        *[f"      {key}: {value}" for key, value in selector],
        "  template:",
        "    metadata:",
        "      labels:",
        *[f"        {key}: {value}" for key, value in selector],
        "    spec:",
        "      securityContext:",
        "        runAsNonRoot: true",
        "      containers:",
        f"        - name: {service.name}",
        # Bare name: the overlay's images transformer supplies registry and tag.
        f"          image: {service.name}",
        "          # Correct only while the image tag is immutable, which is what",
        "          # delivery.image_tag asks you to guarantee. Against a moving tag this",
        "          # silently runs whatever a node already cached.",
        "          imagePullPolicy: IfNotPresent",
        "          ports:",
    ]
    for port in ports:
        lines += ["            - name: http", f"              containerPort: {port}"]
    env_lines = _env_entries(appspec, service)
    if env_lines:
        lines.append("          env:")
        lines += env_lines
    # #24: liveness and readiness are separate probes with separate timings.
    for probe in sorted(probes, key=lambda p: p.role):
        check = (
            ["            tcpSocket:", f"              port: {probe.port}"]
            if probe.kind == "tcp"
            else [
                "            httpGet:",
                f"              path: {probe.path}",
                f"              port: {probe.port}",
            ]
        )
        lines += [
            f"          {probe.role}Probe:",
            *check,
            f"            initialDelaySeconds: {probe.initial_delay_seconds}",
            f"            periodSeconds: {probe.period_seconds}",
        ]
    lines += [
        "          resources:",
        "            requests:",
        *[f"              {k}: {v}" for k, v in sorted(service.resources.requests.items())],
        "            limits:",
        *[f"              {k}: {v}" for k, v in sorted(service.resources.limits.items())],
        "          securityContext:",
        "            allowPrivilegeEscalation: false",
        "            readOnlyRootFilesystem: false",
        "            capabilities:",
        "              drop:",
        "                - ALL",
    ]
    return yaml_block(lines)


def render_service(appspec: AppSpec, service: Service) -> str:
    selector = labels(appspec, service)
    lines = [
        BANNER,
        "apiVersion: v1",
        "kind: Service",
        "metadata:",
        f"  name: {service.name}",
        "  labels:",
        *[f"    {key}: {value}" for key, value in selector],
        "spec:",
        "  type: ClusterIP",
        "  selector:",
        *[f"    {key}: {value}" for key, value in selector],
        "  ports:",
    ]
    for port in service.ports or [serving_port(service)]:
        lines += [
            "    - name: http",
            f"      port: {port}",
            "      targetPort: http",
            "      protocol: TCP",
        ]
    return yaml_block(lines)


def render_ingress(appspec: AppSpec) -> str:
    lines = [BANNER]
    if all(route.host is None for route in appspec.routes):
        lines += [
            f"# offramp: unresolved gap {gap_id('route', 'host')}",
            "#   No hostname is set, so this rule matches any host that reaches the",
            "#   ingress controller and no certificate can be issued.",
        ]
    if appspec.delivery.ingress_class is None:
        lines += [
            f"# offramp: unresolved gap {gap_id('delivery', 'ingress_class')}",
            "#   No ingressClassName is set, so the cluster's default IngressClass is used.",
        ]
    lines += [
        "apiVersion: networking.k8s.io/v1",
        "kind: Ingress",
        "metadata:",
        f"  name: {app_name(appspec)}",
        "  labels:",
        f"    app.kubernetes.io/part-of: {app_name(appspec)}",
        "spec:",
    ]
    if appspec.delivery.ingress_class:
        lines.append(f"  ingressClassName: {appspec.delivery.ingress_class}")
    hosts = sorted({route.host for route in appspec.routes if route.host})
    lines.append("  rules:")
    # Longest path first: a controller matching in order must see /api before /, or
    # every API call is served the frontend bundle.
    ordered = sorted(appspec.routes, key=lambda r: (-len(r.path), r.path))
    for host in hosts or [None]:
        lines.append(f"    - host: {host}" if host else "    - http:")
        if host:
            lines.append("      http:")
        indent = "        " if host else "        "
        lines.append(f"{indent}paths:")
        for route in ordered:
            if host and route.host != host:
                continue
            lines += [
                f"{indent}  - path: {route.path}",
                f"{indent}    pathType: Prefix",
                f"{indent}    backend:",
                f"{indent}      service:",
                f"{indent}        name: {route.service}",
                f"{indent}        port:",
            ]
            # #3: a null port means "wire to the Service's named port", so the
            # detector never has to know a number that belongs to the renderer.
            if route.port is None:
                lines.append(f"{indent}          name: http")
            else:
                lines.append(f"{indent}          number: {route.port}")
    if appspec.routes and any(route.tls for route in appspec.routes) and hosts:
        lines += ["  tls:", "    - hosts:"]
        lines += [f"        - {host}" for host in hosts]
        lines.append(f"      secretName: {app_name(appspec)}-tls")
    return yaml_block(lines)


def render_base_kustomization(appspec: AppSpec, resources: list[str]) -> str:
    return yaml_block(
        [
            BANNER,
            "apiVersion: kustomize.config.k8s.io/v1beta1",
            "kind: Kustomization",
            "resources:",
            *[f"  - {name}" for name in sorted(resources)],
        ]
    )


# ---------------------------------------------------------------------------
# Overlay and GitOps
# ---------------------------------------------------------------------------

def render_namespace(appspec: AppSpec, environment) -> str:
    lines = [BANNER]
    if environment.namespace is None:
        lines += [
            f"# offramp: unresolved gap "
            f"{gap_id('environment', environment.name, 'namespace')}",
            "#   Derived from the app name, which is itself unanswered.",
        ]
    return yaml_block(
        lines
        + [
            "apiVersion: v1",
            "kind: Namespace",
            "metadata:",
            f"  name: {namespace_of(appspec, environment)}",
            "  labels:",
            f"    app.kubernetes.io/part-of: {app_name(appspec)}",
        ]
    )


def render_overlay_kustomization(appspec: AppSpec, environment) -> str:
    lines = [
        BANNER,
        f"# Overlay: {environment.name}",
        "apiVersion: kustomize.config.k8s.io/v1beta1",
        "kind: Kustomization",
        f"namespace: {namespace_of(appspec, environment)}",
        "resources:",
        "  - ../../base",
        "  - namespace.yaml",
    ]
    registry = appspec.delivery.image_registry
    if registry is None:
        registry = PLACEHOLDER_REGISTRY.value
        lines += marker(
            PLACEHOLDER_REGISTRY,
            f"{registry} is not a registry. Replace it before applying.",
        )
    tag = appspec.delivery.image_tag
    if tag is None:
        tag = environment.name
        lines += [
            f"# offramp: unresolved gap {gap_id('delivery', 'image_tag')}",
            f"#   Using the environment name, so every build overwrites '{tag}'.",
        ]
    lines.append("images:")
    for service in sorted(appspec.services, key=lambda s: s.name):
        lines += [
            f"  - name: {service.name}",
            f"    newName: {registry}/{app_name(appspec)}/{service.name}",
            f"    newTag: {tag}",
        ]
    if environment.replicas:
        lines += ["patches:", "  - path: replicas.yaml"]
    return yaml_block(lines)


def render_replicas_patch(appspec: AppSpec, environment) -> str | None:
    if not environment.replicas:
        return None
    documents = []
    for name in sorted(environment.replicas):
        documents += [
            "---",
            "apiVersion: apps/v1",
            "kind: Deployment",
            "metadata:",
            f"  name: {name}",
            "spec:",
            f"  replicas: {environment.replicas[name]}",
        ]
    return yaml_block([BANNER] + documents[1:])


def render_applicationset(appspec: AppSpec) -> str:
    lines = [BANNER]
    repo = appspec.delivery.gitops_repo_url
    if repo is None:
        repo = PLACEHOLDER_REPO.value
        lines += marker(
            PLACEHOLDER_REPO,
            "ArgoCD cannot resolve this. Replace it with the git repository you",
            "commit this tree to.",
        )
    name = app_name(appspec)
    return yaml_block(
        lines
        + [
            "apiVersion: argoproj.io/v1alpha1",
            "kind: ApplicationSet",
            "metadata:",
            f"  name: {name}",
            "  namespace: argocd",
            "spec:",
            "  generators:",
            "    - git:",
            f"        repoURL: {repo}",
            "        revision: HEAD",
            "        directories:",
            "          - path: k8s/overlays/*",
            "  template:",
            "    metadata:",
            f"      name: '{name}-{{{{path.basename}}}}'",
            "    spec:",
            "      project: default",
            "      source:",
            f"        repoURL: {repo}",
            "        targetRevision: HEAD",
            "        path: '{{path}}'",
            "      destination:",
            f"        server: {appspec.delivery.target_cluster}",
            f"        namespace: '{name}-{{{{path.basename}}}}'",
            "      syncPolicy:",
            "        automated:",
            "          prune: true",
            "          selfHeal: true",
            "        syncOptions:",
            "          - CreateNamespace=false",
        ]
    )


def render_readme(appspec: AppSpec) -> str:
    """#14: where the output tree sits, which RFC-0001 never says.

    The RFC calls the tool a scaffolder of a deployment repository for a greenfield
    user, and separately has it emit a Dockerfile per service. Those want opposite
    things: a Dockerfile must be able to COPY application source, so it cannot live
    in a repository the source is not in. This file records the resolution.
    """
    services = sorted(appspec.services, key=lambda s: s.name)
    return yaml_block(
        [
            "# Generated by offramp",
            "",
            "Every file listed in `manifest.json` was written by a renderer from the",
            "AppSpec. Do not edit them: `verify` re-renders and diffs, and `render`",
            "refuses to overwrite a file whose hash has changed since the last run.",
            "Change the AppSpec, or answer the gap, and render again.",
            "",
            "## Where this tree lives",
            "",
            "It is rooted at your application repository, not in a separate deployment",
            "repository. The Dockerfiles need to COPY application source, and the",
            "frontend image additionally needs `services/frontend/nginx.conf` from this",
            "generated tree, so one build context has to contain both. That context is",
            "the repository root.",
            "",
            "```",
            *[
                f"docker build -f services/{s.name}/Dockerfile -t {s.name} ."
                for s in services
            ],
            "```",
            "",
            "ArgoCD watches this same repository; the ApplicationSet's `path` glob points",
            "at `k8s/overlays/*`.",
            "",
            "## Deploying a new build",
            "",
            "The image tag is a per-build fact, and this tree is a pure function of the",
            "AppSpec, so the tag reaches it the same way every other value does: as an",
            "answer. Do not edit `newTag` in the overlay -- `verify` will report it, and it",
            "is right to, because it cannot tell your pipeline apart from something that",
            "edited generated output it should not have.",
            "",
            "```",
            "scan.py  <repo> --out .offramp/scan --answers answers.json",
            "# write a one-entry plan setting delivery.image_tag to the SHA you just built",
            "apply.py plan.json --scan .offramp/scan --repo . --now \"$(date -Iseconds)\" \\",
            "         --answers answers.json --out answers.json \\",
            "         --accept-resolve delivery.image_tag --accepted-by ci",
            "scan.py  <repo> --out .offramp/scan --answers answers.json",
            "render.py .offramp/scan/appspec.json --out . --force",
            "git commit -am \"deploy <sha>\"",
            "```",
            "",
            "No model and no API key are involved. Answers written this way are marked",
            "`accepted_by: ci`, so a reviewer can still see which answers a person decided.",
            "",
            "## What is not here",
            "",
            "The gap report. It lives with the scan output, because a renderer is given",
            "the AppSpec and gaps are not in it. Read it before applying anything: until",
            "every blocking gap is answered this tree contains placeholders that are",
            "deliberately invalid.",
        ]
    )


# ---------------------------------------------------------------------------
# The whole tree
# ---------------------------------------------------------------------------

def render_tree(appspec: AppSpec) -> dict[str, str]:
    """AppSpec -> every file in the output tree, keyed by relative POSIX path."""
    files: dict[str, str] = {
        ".dockerignore": render_dockerignore(appspec),
        ".offramp/README.md": render_readme(appspec),
    }
    base_resources: list[str] = []

    for service in sorted(appspec.services, key=lambda s: s.name):
        files[f"services/{service.name}/Dockerfile"] = render_dockerfile(appspec, service)
        if service.build.output_dir:
            files[f"services/{service.name}/nginx.conf"] = render_nginx_conf(appspec, service)

        configmap = render_configmap(appspec, service)
        if configmap:
            name = f"{service.name}-configmap.yaml"
            files[f"k8s/base/{name}"] = configmap
            base_resources.append(name)

        name = f"{service.name}-deployment.yaml"
        files[f"k8s/base/{name}"] = render_deployment(appspec, service)
        base_resources.append(name)

        name = f"{service.name}-service.yaml"
        files[f"k8s/base/{name}"] = render_service(appspec, service)
        base_resources.append(name)

    if appspec.routes:
        files["k8s/base/ingress.yaml"] = render_ingress(appspec)
        base_resources.append("ingress.yaml")

    files["k8s/base/kustomization.yaml"] = render_base_kustomization(appspec, base_resources)

    for environment in sorted(appspec.environments, key=lambda e: e.name):
        prefix = f"k8s/overlays/{environment.name}"
        files[f"{prefix}/kustomization.yaml"] = render_overlay_kustomization(appspec, environment)
        files[f"{prefix}/namespace.yaml"] = render_namespace(appspec, environment)
        patch = render_replicas_patch(appspec, environment)
        if patch:
            files[f"{prefix}/replicas.yaml"] = patch

    files["gitops/applicationset.yaml"] = render_applicationset(appspec)
    return dict(sorted(files.items()))
